apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: agent
  name: agent
spec:
  ports:
  - port: 34000
    protocol: TCP
    targetPort: 34000
  selector:
    app: agent
status:
  loadBalancer: {}
