apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"cassandra"},"name":"cassandra","namespace":"haystack-apps"},"spec":{"ports":[{"port":9042,"targetPort":9042}],"selector":{"k8s-app":"cassandra"}}}
  creationTimestamp: null
  labels:
    k8s-app: cassandra
  name: cassandra
  selfLink: /api/v1/namespaces/haystack-apps/services/cassandra
spec:
  ports:
  - port: 9042
    protocol: TCP
    targetPort: 9042
  selector:
    k8s-app: cassandra
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
