apiVersion: v1
data:
  actions.yml: |-
    actions:
      1:
        action: delete_indices
        options:
          ignore_empty_list: True
          timeout_override:
          continue_if_exception: False
          disable_action: False
        filters:
        - filtertype: pattern
          kind: prefix
          value: service-metadata-
          exclude:
        - filtertype: age
          source: name
          direction: older
          timestring: "%Y-%m-%d"
          unit: days
          unit_count: 4
          exclude:
  curator.yml: |-
    client:
      hosts:
        - elasticsearch
      port: 9200
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      aws_key:
      aws_secret_key:
      aws_region:
      ssl_no_validate: False
      http_auth:
      timeout: 30
      master_only: False
    logging:
      loglevel: DEBUG
      logfile:
      logformat: default
      blacklist: [elasticsearch, urllib3]
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    app: curator-es-service-metadata-index-store
  name: curator-es-service-metadata-index-store
