apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"elasticsearch"},"name":"elasticsearch","namespace":"haystack-apps"},"spec":{"ports":[{"port":9200,"targetPort":9200}],"selector":{"k8s-app":"elasticsearch"}}}
  creationTimestamp: null
  labels:
    k8s-app: elasticsearch
  name: elasticsearch
  selfLink: /api/v1/namespaces/haystack-apps/services/elasticsearch
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    k8s-app: elasticsearch
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
