apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{},"labels":{"k8s-app":"elasticsearch"},"name":"elasticsearch","namespace":"haystack-apps"},"spec":{"replicas":1,"selector":{"matchLabels":{"k8s-app":"elasticsearch"}},"template":{"metadata":{"labels":{"k8s-app":"elasticsearch"}},"spec":{"containers":[{"env":[{"name":"ES_JAVA_OPTS","value":"-Xms512m -Xmx512m"}],"image":"elasticsearch:5-alpine","name":"elasticsearch","resources":{"limits":{"memory":"1224Mi"},"requests":{"cpu":"100m","memory":"1224Mi"}}}],"nodeSelector":{"kubernetes.io/hostname":"minikube"}}}}}
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: elasticsearch
  name: elasticsearch
  selfLink: /apis/extensions/v1beta1/namespaces/haystack-apps/deployments/elasticsearch
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: elasticsearch
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: elasticsearch
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        image: elasticsearch:5-alpine
        imagePullPolicy: IfNotPresent
        name: elasticsearch
        resources:
          limits:
            memory: 1224Mi
          requests:
            cpu: 100m
            memory: 1224Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: minikube
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
