apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    k8s-app: elasticsearch
  name: elasticsearch
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    k8s-app: elasticsearch
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
