apiVersion: batch/v1
kind: Job
metadata:
  annotations:
  creationTimestamp: null
  labels:
    job-name: es-whitelist
  name: es-whitelist
  selfLink: /apis/batch/v1/namespaces/haystack-apps/jobs/es-whitelist
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        job-name: es-whitelist
    spec:
      containers:
      - args:
        - -XPUT
        - -H
        - 'Content-Type: application/json'
        - -d
        - '@/data/whitelist.json'
        - http://elasticsearch:9200/reload-configs/indexing-fields/1
        command:
        - curl
        image: yauritux/busybox-curl
        imagePullPolicy: Always
        name: es-whitelist
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: whitelist-json
        name: data
status: {}
