apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"haystack-ui"},"name":"haystack-ui","namespace":"haystack-apps"},"spec":{"ports":[{"port":80,"targetPort":8080}],"selector":{"k8s-app":"haystack-ui"}}}
  creationTimestamp: null
  labels:
    k8s-app: haystack-ui
  name: haystack-ui
  selfLink: /api/v1/namespaces/haystack-apps/services/haystack-ui
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: haystack-ui
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
