apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{},"labels":{"k8s-app":"haystack-ui"},"name":"haystack-ui","namespace":"haystack-apps"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"k8s-app":"haystack-ui"}},"template":{"metadata":{"labels":{"k8s-app":"haystack-ui"}},"spec":{"containers":[{"env":[{"name":"HAYSTACK_OVERRIDES_CONFIG_PATH","value":"/config/haystack-ui.json"}],"image":"expediadotcom/haystack-ui:1.1","name":"haystack-ui","resources":{"limits":{"cpu":"1000m","memory":"250Mi"},"requests":{"cpu":"100m","memory":"250Mi"}},"volumeMounts":[{"mountPath":"/config","name":"config-volume"}]}],"nodeSelector":{"kubernetes.io/hostname":"minikube"},"volumes":[{"configMap":{"name":"ui-fb68cf490de8bb9c228b0167dfe5b4d8e1edfc4b"},"name":"config-volume"}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: haystack-ui
  name: haystack-ui
  selfLink: /apis/extensions/v1beta1/namespaces/haystack-apps/deployments/haystack-ui
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: haystack-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: haystack-ui
    spec:
      containers:
      - env:
        - name: HAYSTACK_OVERRIDES_CONFIG_PATH
          value: /config/haystack-ui.json
        image: expediadotcom/haystack-ui:1.1
        imagePullPolicy: IfNotPresent
        name: haystack-ui
        resources:
          limits:
            cpu: "1"
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 250Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config-volume
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: minikube
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: ui-fb68cf490de8bb9c228b0167dfe5b4d8e1edfc4b
        name: config-volume
status: {}
