apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"kafka-service"},"name":"kafka-service","namespace":"haystack-apps"},"spec":{"ports":[{"port":9092,"targetPort":9092}],"selector":{"k8s-app":"kafka-service"}}}
  creationTimestamp: null
  labels:
    k8s-app: kafka-service
  name: kafka-service
  selfLink: /api/v1/namespaces/haystack-apps/services/kafka-service
spec:
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    k8s-app: kafka-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
