apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    k8s-app: kafka-service
  name: kafka-service
spec:
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    k8s-app: kafka-service
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
