apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{},"labels":{"k8s-app":"kafka-service"},"name":"kafka-service","namespace":"haystack-apps"},"spec":{"replicas":1,"selector":{"matchLabels":{"k8s-app":"kafka-service"}},"template":{"metadata":{"labels":{"k8s-app":"kafka-service"}},"spec":{"containers":[{"env":[{"name":"KAFKA_ADVERTISED_HOST_NAME","value":"192.168.64.5"},{"name":"KAFKA_ADVERTISED_PORT","value":"9092"},{"name":"KAFKA_ZOOKEEPER_CONNECT","value":"zookeeper:2181"},{"name":"KAFKA_CREATE_TOPICS","value":"proto-spans:1:1,metricpoints:1:1,mdm:1:1,span-buffer:1:1,graph-nodes:1:1,ewma-metrics:1:1,constant-metrics:1:1,pewma-metrics:1:1,anomalies:1:1,aa-metrics:1:1,mapped-metrics:1:1"},{"name":"KAFKA_LOG_MESSAGE_TIMESTAMP_TYPE","value":"LogAppendTime"},{"name":"KAFKA_HEAP_OPTS","value":"-Xmx512m -Xms512m"}],"image":"wurstmeister/kafka:0.11.0.1","name":"kafka-service","ports":[{"containerPort":9092,"hostPort":9092}],"resources":{"limits":{"memory":"1224Mi"},"requests":{"cpu":"100m","memory":1224}}}],"nodeSelector":{"kubernetes.io/hostname":"minikube"}}}}}
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: kafka-service
  name: kafka-service
  selfLink: /apis/extensions/v1beta1/namespaces/haystack-apps/deployments/kafka-service
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kafka-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: kafka-service
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 192.168.64.5
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        - name: KAFKA_CREATE_TOPICS
          value: proto-spans:1:1,metricpoints:1:1,mdm:1:1,span-buffer:1:1,graph-nodes:1:1,ewma-metrics:1:1,constant-metrics:1:1,pewma-metrics:1:1,anomalies:1:1,aa-metrics:1:1,mapped-metrics:1:1
        - name: KAFKA_LOG_MESSAGE_TIMESTAMP_TYPE
          value: LogAppendTime
        - name: KAFKA_HEAP_OPTS
          value: -Xmx512m -Xms512m
        image: wurstmeister/kafka:0.11.0.1
        imagePullPolicy: IfNotPresent
        name: kafka-service
        ports:
        - containerPort: 9092
          hostPort: 9092
          protocol: TCP
        resources:
          limits:
            memory: 1224Mi
          requests:
            cpu: 100m
            memory: "1224"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: minikube
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
