apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    k8s-app: metrictank
  name: metrictank
spec:
  ports:
  - port: 6060
    protocol: TCP
    targetPort: 6060
  selector:
    k8s-app: metrictank
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
