apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: metrictank
  name: metrictank
  selfLink: /apis/extensions/v1beta1/namespaces/haystack-apps/deployments/metrictank
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: metrictank
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: metrictank
    spec:
      containers:
      - env:
        - name: MT_HTTP_MULTI_TENANT
          value: "false"
        - name: MT_CARBON_IN_ENABLED
          value: "false"
        - name: MT_KAFKA_MDM_IN_ENABLED
          value: "true"
        - name: MT_CASSANDRA_ADDRS
          value: cassandra:9042
        - name: MT_KAFKA_MDM_IN_BROKERS
          value: kafka-service:9092
        - name: MT_CASSANDRA_IDX_HOSTS
          value: cassandra:9042
        - name: MT_STATS_ADDR
          value: monitoring-influxdb-graphite:2003
        - name: MT_MEMORY_IDX_TAG_SUPPORT
          value: "true"
        - name: MT_PROFTRIGGER_PATH
          value: /var/lib/metrictank/$HOSTNAME
        workingDir: /tmp
        image: grafana/metrictank:0.10.1
        imagePullPolicy: IfNotPresent
        name: metrictank
        resources:
          limits:
            cpu: "1"
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 250Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/metrictank
          name: storage
      volumes:
      - emptyDir: {}
        name: storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
