apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"metrictank"},"name":"metrictank","namespace":"haystack-apps"},"spec":{"ports":[{"port":6060,"targetPort":6060}],"selector":{"k8s-app":"metrictank"}}}
  creationTimestamp: null
  labels:
    k8s-app: metrictank
  name: metrictank
  selfLink: /api/v1/namespaces/haystack-apps/services/metrictank
spec:
  ports:
  - port: 6060
    protocol: TCP
    targetPort: 6060
  selector:
    k8s-app: metrictank
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
