apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: pitchfork
  name: pitchfork
  selfLink: /apis/extensions/v1beta1/namespaces/haystack-apps/deployments/pitchfork
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: pitchfork
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: pitchfork
    spec:
      containers:
      - env:
        - name: PITCHFORK_FORWARDERS_ZIPKIN_HTTP_ENDPOINT
          value: http://zipkin:9411/api/v2/spans
        - name: PITCHFORK_FORWARDERS_ZIPKIN_HTTP_ENABLED
          value: "true"
        - name: PITCHFORK_FORWARDERS_LOGGING_ENABLED
          value: "true"
        - name: PITCHFORK_FORWARDERS_LOGGING_LOG_FULL_SPAN
          value: "true"
        - name: PITCHFORK_INGRESS_KAFKA_ENABLED
          value: "true"
        image: hotelsdotcom/pitchfork
        imagePullPolicy: IfNotPresent
        name: pitchfork
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 1
      terminationGracePeriodSeconds: 30
status: {}
