apiVersion: v1
data:
  trace-reader.conf: |
    service {
        port = 8080
        ssl {
          enabled = false
          cert.path = ""
          private.key.path = ""
        }
        max.message.size = 52428800 # 50MB in bytes
    }

    backend {
      client {
        host = "localhost"
        port = 8090
      }
    }

    elasticsearch {
      client {
        endpoint = "http://elasticsearch:9200"
        conn.timeout.ms = 10000
        read.timeout.ms = 30000
      }
      index {
        spans {
          name.prefix = "haystack-traces"
          type = "spans"
          hour.bucket = 6
          hour.ttl = 72 // 3 * 24 hours
          use.root.doc.starttime = true
        }
        service.metadata {
          enabled = true
          name = "service-metadata"
          type = "metadata"
        }
      }
    }

    trace {
      validators {
        sequence = [
          "com.expedia.www.haystack.trace.reader.readers.validators.TraceIdValidator"
        ]
      }

      transformers {
        pre {
          sequence = [
            "com.expedia.www.haystack.trace.reader.readers.transformers.DeDuplicateSpanTransformer"
            "com.expedia.www.haystack.trace.reader.readers.transformers.ClientServerEventLogTransformer"
          ]
        }
        post {
          sequence = [
            "com.expedia.www.haystack.trace.reader.readers.transformers.PartialSpanTransformer"
            "com.expedia.www.haystack.trace.reader.readers.transformers.ServerClientSpanMergeTransformer"
            "com.expedia.www.haystack.trace.reader.readers.transformers.InvalidRootTransformer"
            "com.expedia.www.haystack.trace.reader.readers.transformers.InvalidParentTransformer"
            "com.expedia.www.haystack.trace.reader.readers.transformers.ClockSkewTransformer"
            "com.expedia.www.haystack.trace.reader.readers.transformers.SortSpanTransformer"
          ]
        }
      }
    }

    reload {
      tables {
        index.fields.config = "indexing-fields"
      }
      config {
        endpoint = "http://elasticsearch:9200"
        database.name = "reload-configs"
      }
      startup.load = true
      interval.ms = 60000 # -1 will imply 'no reload'
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: reader-48f3f74a468b0017ed9cf3ab1fc882c322c2dfd6
  selfLink: /api/v1/namespaces/haystack-apps/configmaps/reader-48f3f74a468b0017ed9cf3ab1fc882c322c2dfd6
