apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: span-timeseries-transformer
  name: span-timeseries-transformer
  selfLink: /apis/extensions/v1beta1/namespaces/haystack-apps/deployments/span-timeseries-transformer
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: span-timeseries-transformer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: span-timeseries-transformer
    spec:
      containers:
      - env:
        - name: HAYSTACK_OVERRIDES_CONFIG_PATH
          value: /config/span-timeseries-transformer.conf
        - name: HAYSTACK_GRAPHITE_HOST
          value: monitoring-influxdb-graphite.kube-system.svc
        - name: HAYSTACK_GRAPHITE_PORT
          value: "2003"
        - name: HAYSTACK_GRAPHITE_ENABLED
          value: "false"
        - name: JAVA_XMS
          value: 200m
        - name: JAVA_XMX
          value: 200m
        image: zoidbergwill/haystack-span-timeseries-transformer
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - grep
            - "true"
            - /app/isHealthy
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: span-timeseries-transformer
        resources:
          limits:
            cpu: "1"
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 250Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: transformer-658ea1e33f1104d5b898cc42b21c51debb350a21
        name: config-volume
status: {}
