apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1beta2","kind":"Deployment","metadata":{"annotations":{},"labels":{"k8s-app":"timeseries-aggregator"},"name":"timeseries-aggregator","namespace":"haystack-apps"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"k8s-app":"timeseries-aggregator"}},"template":{"metadata":{"labels":{"k8s-app":"timeseries-aggregator"}},"spec":{"containers":[{"env":[{"name":"HAYSTACK_OVERRIDES_CONFIG_PATH","value":"/config/timeseries-aggregator.conf"},{"name":"HAYSTACK_GRAPHITE_HOST","value":"monitoring-influxdb-graphite.kube-system.svc"},{"name":"HAYSTACK_GRAPHITE_PORT","value":"2003"},{"name":"HAYSTACK_GRAPHITE_ENABLED","value":"false"},{"name":"JAVA_XMS","value":"200m"},{"name":"JAVA_XMX","value":"200m"}],"image":"expediadotcom/haystack-timeseries-aggregator:1.1","livenessProbe":{"exec":{"command":["grep","true","/app/isHealthy"]},"failureThreshold":6,"initialDelaySeconds":30,"periodSeconds":5},"name":"timeseries-aggregator","resources":{"limits":{"cpu":"1000m","memory":"250Mi"},"requests":{"cpu":"100m","memory":"250Mi"}},"volumeMounts":[{"mountPath":"/config","name":"config-volume"}]}],"nodeSelector":{"kubernetes.io/hostname":"minikube"},"volumes":[{"configMap":{"name":"aggregator-011a56343fed5381c409b57b65cf4bfad49730cc"},"name":"config-volume"}]}}}}
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: timeseries-aggregator
  name: timeseries-aggregator
  selfLink: /apis/extensions/v1beta1/namespaces/haystack-apps/deployments/timeseries-aggregator
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: timeseries-aggregator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: timeseries-aggregator
    spec:
      containers:
      - env:
        - name: HAYSTACK_OVERRIDES_CONFIG_PATH
          value: /config/timeseries-aggregator.conf
        - name: HAYSTACK_GRAPHITE_HOST
          value: monitoring-influxdb-graphite.kube-system.svc
        - name: HAYSTACK_GRAPHITE_PORT
          value: "2003"
        - name: HAYSTACK_GRAPHITE_ENABLED
          value: "false"
        - name: JAVA_XMS
          value: 200m
        - name: JAVA_XMX
          value: 200m
        image: expediadotcom/haystack-timeseries-aggregator:1.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - grep
            - "true"
            - /app/isHealthy
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        name: timeseries-aggregator
        resources:
          limits:
            cpu: "1"
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 250Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config-volume
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: minikube
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: aggregator-011a56343fed5381c409b57b65cf4bfad49730cc
        name: config-volume
status: {}
