apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: trace-indexer
  name: trace-indexer
  selfLink: /apis/extensions/v1beta1/namespaces/haystack-apps/deployments/trace-indexer
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: trace-indexer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: trace-indexer
    spec:
      containers:
      - env:
        - name: HAYSTACK_PROP_CASSANDRA_ENDPOINTS
          value: cassandra
        - name: HAYSTACK_GRAPHITE_HOST
          value: monitoring-influxdb-graphite.kube-system.svc
        - name: HAYSTACK_GRAPHITE_PORT
          value: "2003"
        - name: HAYSTACK_GRAPHITE_ENABLED
          value: "false"
        - name: JAVA_XMS
          value: 200m
        - name: JAVA_XMX
          value: 200m
        image: expediadotcom/haystack-trace-backend-cassandra:316f53fb22b01984099db5c2b99049b703483082
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /bin/grpc_health_probe
            - -addr=:8090
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 5
        name: storage-backend-cassandra
        resources:
          limits:
            cpu: 500m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 250Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - env:
        - name: HAYSTACK_OVERRIDES_CONFIG_PATH
          value: /config/trace-indexer.conf
        - name: HAYSTACK_GRAPHITE_HOST
          value: monitoring-influxdb-graphite.kube-system.svc
        - name: HAYSTACK_GRAPHITE_PORT
          value: "2003"
        - name: HAYSTACK_GRAPHITE_ENABLED
          value: "false"
        - name: JAVA_XMS
          value: 200m
        - name: JAVA_XMX
          value: 200m
        image: expediadotcom/haystack-trace-indexer:316f53fb22b01984099db5c2b99049b703483082
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - grep
            - "true"
            - /app/isHealthy
          failureThreshold: 6
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        name: trace-indexer
        resources:
          limits:
            cpu: "1"
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 250Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /config
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: indexer-fd354acb1e5ab3440a27c570d2a2b6561b4c96de
        name: config-volume
status: {}
