apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    k8s-app: trace-reader
  name: trace-reader
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: trace-reader
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
