apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"trace-reader"},"name":"trace-reader","namespace":"haystack-apps"},"spec":{"ports":[{"port":8080,"targetPort":8080}],"selector":{"k8s-app":"trace-reader"}}}
  creationTimestamp: null
  labels:
    k8s-app: trace-reader
  name: trace-reader
  selfLink: /api/v1/namespaces/haystack-apps/services/trace-reader
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    k8s-app: trace-reader
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
