apiVersion: v1
data:
  whitelist.json: |-
    {
        "fields": [{
            "name": "error",
            "type": "string",
            "enabled": true,
            "searchContext": "trace"
        },{
          "name": "traceId",
          "type": "string",
          "enabled": true,
          "searchContext": "trace"
        }]
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"whitelist.json":"{\n    \"fields\": [{\n        \"name\": \"error\",\n        \"type\": \"string\",\n        \"enabled\": true,\n        \"searchContext\": \"trace\"\n    }]\n}"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"whitelist-json","namespace":"haystack-apps"}}
  creationTimestamp: null
  name: whitelist-json
  selfLink: /api/v1/namespaces/haystack-apps/configmaps/whitelist-json
