apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: zipkin
  name: zipkin
  selfLink: /apis/extensions/v1beta1/namespaces/haystack-apps/deployments/zipkin
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: zipkin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: zipkin
    spec:
      containers:
      - env:
        - name: MAX_HEAP_SIZE
          value: 512m
        - name: HEAP_NEWSIZE
          value: 512m
        - name: STORAGE_TYPE
          value: cassandra3
        - name: CASSANDRA_ENSURE_SCHEMA
          value: "true"
        - name: CASSANDRA_CONTACT_POINTS
          value: cassandra
        image: openzipkin/zipkin
        imagePullPolicy: IfNotPresent
        name: zipkin
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 1
      terminationGracePeriodSeconds: 30
status: {}
