apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    k8s-app: zipkin
  name: zipkin
  selfLink: /api/v1/namespaces/haystack-apps/services/zipkin
spec:
  ports:
  - port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    k8s-app: zipkin
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
