apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"k8s-app":"zookeeper"},"name":"zookeeper","namespace":"haystack-apps"},"spec":{"ports":[{"port":2181,"targetPort":2181}],"selector":{"k8s-app":"zookeeper"}}}
  creationTimestamp: null
  labels:
    k8s-app: zookeeper
  name: zookeeper
  selfLink: /api/v1/namespaces/haystack-apps/services/zookeeper
spec:
  ports:
  - port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    k8s-app: zookeeper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
