apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    k8s-app: zookeeper
  name: zookeeper
spec:
  ports:
  - port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    k8s-app: zookeeper
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
