apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    k8s-app: zookeeper
  name: zookeeper
  selfLink: /apis/extensions/v1beta1/namespaces/haystack-apps/deployments/zookeeper
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: zookeeper
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: zookeeper
    spec:
      containers:
      - image: zookeeper:3.4.12
        imagePullPolicy: IfNotPresent
        name: zookeeper
        env:
        - name: ZOO_SERVERS
          value: server.1=0.0.0.0:2888:3888
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /conf
          name: config
        - mountPath: /data
          name: data
        - mountPath: /datalog
          name: datalog
        - mountPath: /logs
          name: logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: config
      - emptyDir: {}
        name: data
      - emptyDir: {}
        name: datalog
      - emptyDir: {}
        name: logs
status: {}
